### ISSUE TITLE
Absolute URIs break when daemon or container behind proxy

### ISSUE THREAD

**Issue by mozai** [deadc0de6/uad#1]
Version: 0.5.6

What I did:
* `./uad -host 127.0.0.1 -port 5044 -max-upload 100M /srv/uad`
* added these lines to nginx
  ```
  location /depot/ {
    client_max_body_size 100M ;
    proxy_pass           http://127.0.0.1:5044/ ;
  }
  ```

What I expected:
* uad works at https://offloader-hostname/uad/

What I saw:
* uad webpage appears at https://offloader-hostname/uad/
* download links are broken with "404 Not Found", webserver log says the requests are "GET /files/name-of-file"
* upload attempts show a brief flicker of progress bar, browser console says it got a "404 Not Found" error.

Suggestions:
* use relative paths in page.html instead of absolute paths .  This works for downloading when I change `<a href="{{.WPath}}">` to `<a href=".{{.WPath}}">`  on line 98
* using relative path for uploading javascript too, chaning lines 166 and 204 from "/upload" to "./upload".
* maybe some helpful text on how to set up nginx / traefik for proxying?  Docker containers aren't always naked on the internet, and it's better/easier to have a proxy handle SSL encryption than try to add cert handilng to uad, and I don't want to admit to how much time was eaten by the "client_max_body_size" thing.

**Comment by deadc0de6** [comment]
Thanks for reporting this. I'm using uad behind [nginx-proxy-manager](https://nginxproxymanager.com/) without any problem.
Here's the config generated by nginx-proxy-manager:
```
server {
  set $forward_scheme http;
  set $server         "uad";
  set $port           6969;
  listen 80;
  server_name uad.somedomain.com;
  access_log /data/logs/proxy_host-7.log proxy;
  location / {
    # Proxy!
    include conf.d/include/proxy.conf;
  }
  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

Here are the configs used by nginx-proxy-manager: [proxy.conf](https://github.com/NginxProxyManager/nginx-proxy-manager/blob/develop/docker/rootfs/etc/nginx/conf.d/include/proxy.conf)
```
add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $remote_addr;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;
```

I will add some doc on how to use uad with a reverse proxy.

I wasn't however able to reproduce your issue with relative path (download/upload broken).
Can you give it a try with some of the configs I pasted above, see if that makes a difference?

**Comment by deadc0de6** [comment]
Indeed, was able to reproduce and your fixes do work. I'm however a bit puzzled on why this happen. 
Anyway, I will look into it and I will release a new version, thanks a lot for your help!

**Comment by deadc0de6** [comment]
Just released v0.5.7 that hopefully fixes your issues. I also added a [reverse proxy doc](https://github.com/deadc0de6/uad#reverse-proxy).

**Comment by mozai** [comment]
nginx default for `client_max_body_size` is 10M, while the default `-max-upload` for uad is 1G, so the client_max_body_size isn't optional for the nginx thing.  Does uad use the extra headers like Host: or X-Real-IP:  ?

**Comment by deadc0de6** [comment]
I updated [the reverse proxy doc](https://github.com/deadc0de6/uad#reverse-proxy). The issue you initially had was related to the fact that you accessed uad from a subpath (`/depot/`). Both use-cases are now documented (subpath and sub-domain).
I also fixed the `client_max_body_size` doc, thanks for pointing that out.
If you happen to test the new version (and proxy directives), please let me know if you encounter any issue.

**Comment by mozai** [comment]
recompiled with v0.6.1, works when the endpoint isn't "/".  Thanks.
